[package]
name = "pythagore"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Jujulego/pythagore"
categories = ["mathematics"]
keywords = ["maths", "point", "vector", "matrix"]
description = "Mathematics tools for simple geometry"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
