[package]
name = "pythagore-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pythagore = { path = "../lib" }
wasm-bindgen = "0.2.86"

[dev-dependencies]
wasm-bindgen-test = "0.3.36"