name: Codecov config

on:
  push:
    paths:
      - .codecov.yml

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Validate codecov yml file
        run: curl --data-binary @.codecov.yml https://codecov.io/validate